export const images = {
  logo: "/images/logo_elporvenir.jpg",
  hero: "/images/hero_platos.jpg",
  carbonara: "/images/carbonara.jpg",
  gastronomia: "/images/gastronomia.jpg",
  rabas: "/images/rabas.jpg",
  esparragos: "/images/esparragos.jpg",
  choripan: "/images/choripan.jpg",
  albondigas: "/images/albondigas.jpg",
  papas: "/images/papas.jpg",
  sorrentinos: "/images/sorrentinos.jpg",
  crocante: "/images/crocante.jpg",
  chipirones: "/images/chipirones.jpg",
  canelones: "/images/canelones.jpg",
  corzetti: "/images/corzetti.jpg",
  hojaldre: "/images/hojaldre.jpg",
  tostada: "/images/tostada.jpg",
  omelet: "/images/omelet.jpg",
  tiradito: "/images/tiradito.jpg",
  paleta: "/images/paleta.jpg",
  pollo: "/images/pollo.jpg",
  sandwich: "/images/sandwich.jpg",
  risotto: "/images/risotto.jpg",
} as const;
